#pragma once

#define ACHORDION_STREAK
#define CAPS_WORD_IDLE_TIMEOUT 0
#define CAPS_WORD_INVERT_ON_SHIFT
#define COMBO_TERM 25
#define EXTRA_SHORT_COMBOS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define MOUSEKEY_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 64
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0
#define PERMISSIVE_HOLD_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY

#if VENDOR_ID != 0x5957
#    define CHORDAL_HOLD
#endif
