#pragma once

#define CAPS_WORD_INVERT_ON_SHIFT
#define COMBO_TERM 25
#define EXTRA_SHORT_COMBOS
#define MOUSEKEY_DELAY          0
#define MOUSEKEY_INTERVAL       16
#define MOUSEKEY_MAX_SPEED      6
#define MOUSEKEY_TIME_TO_MAX    64
#define MOUSEKEY_WHEEL_DELAY    0
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM_PER_KEY
#define TAPPING_TERM 175
